# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# import resource_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 659)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading_frame = QtWidgets.QFrame(self.centralwidget)
        self.heading_frame.setGeometry(QtCore.QRect(10, 10, 1061, 41))
        self.heading_frame.setStyleSheet("position: absolute;\n"
                                         "width: 1895px;\n"
                                         "height: 81px;\n"
                                         "left: 12px;\n"
                                         "top: 15px;\n"
                                         "\n" 
                                         "border-radius: 10px;")
        self.heading_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.heading_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heading_frame.setObjectName("heading_frame")
        self.label_2 = QtWidgets.QLabel(self.heading_frame)
        self.label_2.setGeometry(QtCore.QRect(0, 5, 1061, 31))
        self.label_2.setStyleSheet("position: absolute;\n"
                                   "width: 572px;\n"
                                   "height: 48px;\n"
                                   "left: 680px;\n"
                                   "top: 6px;\n"
                                   "\n"
                                   "font-family: Poppins;\n"
                                   "font-style: normal;\n"
                                   "font-weight: normal;\n"
                                   "font-size: 35px;\n"
                                   "line-height: 61px;\n"
                                   "text-align: center;\n"
                                   "letter-spacing: 0.07em;\n"
                                   "text-transform: uppercase;\n"
                                   "\n"
                                   "text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                   "")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(-1, 49, 1081, 611))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.class_name_frame = QtWidgets.QFrame(self.main_frame)
        self.class_name_frame.setGeometry(QtCore.QRect(269, 20, 541, 101))
        self.class_name_frame.setStyleSheet("#class_name_frame{position: absolute;\n"
                                            "left: 435px;\n"
                                            "right: 429px;\n"
                                            "top: 119px;\n"
                                            "bottom: 756px;\n"
                                            "\n"
                                            "background: rgba(118, 158, 161, 0.4);\n"
                                            "box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                            "border-radius: 10px;}")
        self.class_name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.class_name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.class_name_frame.setObjectName("class_name_frame")
        self.class_name_label = QtWidgets.QLabel(self.class_name_frame)
        self.class_name_label.setGeometry(QtCore.QRect(10, 0, 541, 51))
        self.class_name_label.setStyleSheet("#class_name_label{\n"
                                            "/* ADA */\n"
                                            "\n"
                                            "\n"
                                            "position: absolute;\n"
                                            "width: 266px;\n"
                                            "height: 61px;\n"
                                            "left: 26px;\n"
                                            "top: 21px;\n"
                                            "\n"
                                            "font-family: Poppins;\n"
                                            "font-style: normal;\n"
                                            "font-weight: normal;\n"
                                            "font-size: 25px;\n"
                                            "line-height: 61px;\n"
                                            "letter-spacing: 0.05em;\n"
                                            "\n"
                                            "color: #FFFFFF;\n"
                                            "\n"
                                            "}")
        self.class_name_label.setObjectName("class_name_label")
        self.class_description_label = QtWidgets.QLabel(self.class_name_frame)
        self.class_description_label.setGeometry(QtCore.QRect(10, 40, 531, 61))
        self.class_description_label.setStyleSheet("#class_description_label{\n"
                                                   "/* ADA */\n"
                                                   "\n"
                                                   "\n"
                                                   "position: absolute;\n"
                                                   "width: 266px;\n"
                                                   "height: 61px;\n"
                                                   "left: 26px;\n"
                                                   "top: 21px;\n"
                                                   "\n"
                                                   "font-family: Poppins;\n"
                                                   "font-style: normal;\n"
                                                   "font-weight: normal;\n"
                                                   "font-size: 15px;\n"
                                                   "line-height: 61px;\n"
                                                   "letter-spacing: 0.05em;\n"
                                                   "\n"
                                                   "color: #000000;\n"
                                                   "\n"
                                                   "}")
        self.class_description_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.class_description_label.setObjectName("class_description_label")
        self.assignment_frame = QtWidgets.QFrame(self.main_frame)
        self.assignment_frame.setGeometry(QtCore.QRect(820, 20, 251, 581))
        self.assignment_frame.setAutoFillBackground(False)
        self.assignment_frame.setStyleSheet("#assignment_frame{position: absolute;\n"
                                            "width: 400px;\n"
                                            "right: 13px;\n"
                                            "top: 119px;\n"
                                            "bottom: 10px;\n"
                                            "\n"
                                            "background: rgba(252, 202, 201, 0.6);\n"
                                            "backdrop-filter: blur(4px);\n"
                                            "/* Note: backdrop-filter has minimal browser support */\n"
                                            "\n"
                                            "border-radius: 20px;}")
        self.assignment_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.assignment_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.assignment_frame.setObjectName("assignment_frame")
        self.label_5 = QtWidgets.QLabel(self.assignment_frame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 231, 61))
        self.label_5.setStyleSheet("position: absolute;\n"
                                   "width: 143px;\n"
                                   "height: 62px;\n"
                                   "left: 133px;\n"
                                   "top: 44px;\n"
                                   "\n"
                                   "font-family: Poppins;\n"
                                   "font-style: normal;\n"
                                   "font-weight: normal;\n"
                                   "font-size: 25px;\n"
                                   "line-height: 61px;\n"
                                   "/* identical to box height */\n"
                                   "\n"
                                   "text-align: center;\n"
                                   "letter-spacing: 0.05em;\n"
                                   "\n"
                                   "color: #000000;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.event_frame = QtWidgets.QFrame(self.main_frame)
        self.event_frame.setGeometry(QtCore.QRect(10, 10, 251, 591))
        self.event_frame.setAutoFillBackground(False)
        self.event_frame.setStyleSheet("#event_frame{position: absolute;\n"
                                       "width: 409px;\n"
                                       "left: 12px;\n"
                                       "top: 119px;\n"
                                       "bottom: 9px;\n"
                                       "\n"
                                       "background: rgba(209, 233, 215, 0.6);\n"
                                       "backdrop-filter: blur(4px);\n"
                                       "/* Note: backdrop-filter has minimal browser support */\n"
                                       "\n"
                                       "border-radius: 20px;\n"
                                       "\n"
                                       "}")
        self.event_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.event_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.event_frame.setObjectName("event_frame")
        self.label_4 = QtWidgets.QLabel(self.event_frame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 231, 61))
        self.label_4.setStyleSheet("position: absolute;\n"
                                   "width: 143px;\n"
                                   "height: 62px;\n"
                                   "left: 133px;\n"
                                   "top: 44px;\n"
                                   "\n"
                                   "font-family: Poppins;\n"
                                   "font-style: normal;\n"
                                   "font-weight: normal;\n"
                                   "font-size: 25px;\n"
                                   "line-height: 61px;\n"
                                   "/* identical to box height */\n"
                                   "\n"
                                   "text-align: center;\n"
                                   "letter-spacing: 0.05em;\n"
                                   "\n"
                                   "color: #000000;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.posts_frame = QtWidgets.QFrame(self.main_frame)
        self.posts_frame.setGeometry(QtCore.QRect(269, 129, 541, 471))
        self.posts_frame.setStyleSheet("position: absolute;\n"
                                       "width: 1056px;\n"
                                       "height: 710px;\n"
                                       "left: 438px;\n"
                                       "top: 343px;\n"
                                       "\n"
                                       "background: #FFFFFF;\n"
                                       "mix-blend-mode: hard-light;\n"
                                       "border-radius: 20px;")
        self.posts_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.posts_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.posts_frame.setObjectName("posts_frame")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "College Virtual Space"))
        self.class_name_label.setText(_translate("MainWindow", "Class Name"))
        self.class_description_label.setText(
            _translate("MainWindow", "Class description"))
        self.label_5.setText(_translate("MainWindow", "Assignments"))
        self.label_4.setText(_translate("MainWindow", "Events"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
