# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\tejas\Desktop\22-01-22\components.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1070, 878)
        mainwindow.setStyleSheet("")
        self.post_button = QtWidgets.QPushButton(mainwindow)
        self.post_button.setGeometry(QtCore.QRect(10, 10, 525, 80))
        self.post_button.setMaximumSize(QtCore.QSize(525, 80))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        self.post_button.setFont(font)
        self.post_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.post_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.post_button.setStyleSheet("position: absolute;\n"
"width: 1000px;\n"
"height: 148px;\n"
"left: calc(50% - 1000px/2 + 2px);\n"
"top: calc(50% - 148px/2 + 249px);\n"
"\n"
"background: #FFFFFF;\n"
"border: 2px solid #000000;\n"
"box-sizing: border-box;\n"
"box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 10px;\n"
"")
        self.post_button.setObjectName("post_button")
        self.events_view = QtWidgets.QFrame(mainwindow)
        self.events_view.setGeometry(QtCore.QRect(400, 160, 229, 70))
        self.events_view.setMinimumSize(QtCore.QSize(229, 70))
        self.events_view.setMaximumSize(QtCore.QSize(229, 70))
        self.events_view.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.events_view.setStyleSheet("#events_view{\n"
"position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.events_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.events_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.events_view.setObjectName("events_view")
        self.label_6 = QtWidgets.QLabel(self.events_view)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_6.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 20px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.events_view)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 211, 41))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_7.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.comment_view_frame = QtWidgets.QFrame(mainwindow)
        self.comment_view_frame.setGeometry(QtCore.QRect(530, 460, 461, 70))
        self.comment_view_frame.setMinimumSize(QtCore.QSize(0, 70))
        self.comment_view_frame.setMaximumSize(QtCore.QSize(461, 70))
        self.comment_view_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comment_view_frame.setStyleSheet("*{\n"
"position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.comment_view_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.comment_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.comment_view_frame.setObjectName("comment_view_frame")
        self.comment = QtWidgets.QLabel(self.comment_view_frame)
        self.comment.setGeometry(QtCore.QRect(10, 0, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comment.setFont(font)
        self.comment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comment.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15\n"
"px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.comment.setObjectName("comment")
        self.user = QtWidgets.QLabel(self.comment_view_frame)
        self.user.setGeometry(QtCore.QRect(10, 40, 441, 21))
        self.user.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"\n"
"border:0px;")
        self.user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.user.setObjectName("user")
        self.pushButton = QtWidgets.QPushButton(mainwindow)
        self.pushButton.setGeometry(QtCore.QRect(900, 170, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assests/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(mainwindow)
        self.pushButton_2.setGeometry(QtCore.QRect(940, 400, 40, 40))
        self.pushButton_2.setStyleSheet("*{border-radius:0px;}\n"
":pressed{\n"
"    border: 3px solid  #FF0000;\n"
"boder:10px;\n"
"border-radius: 8px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\tejas\\Desktop\\22-01-22\\assests/icons/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.sign_up_button = QtWidgets.QPushButton(mainwindow)
        self.sign_up_button.setGeometry(QtCore.QRect(390, 280, 425, 40))
        self.sign_up_button.setStyleSheet("*{\n"
"font-family: Inter;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"/* identical to box height */\n"
"\n"
"align-items: center;\n"
"\n"
"/* Grey / Light */\n"
"\n"
"color: white;\n"
"background: #4F4F4F;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
":pressed {\n"
"    border-style: inset;\n"
"    border: 1px solid  #4F4F4F;\n"
"color: #4F4F4F;\n"
"background: #FFFFFF;\n"
"}\n"
"/* Inside auto layout */\n"
"\n"
"")
        self.sign_up_button.setObjectName("sign_up_button")
        self.sign_in_button = QtWidgets.QPushButton(mainwindow)
        self.sign_in_button.setGeometry(QtCore.QRect(390, 330, 425, 40))
        self.sign_in_button.setStyleSheet("*{\n"
"font-family: Inter;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"align-items: center;\n"
"border-style: inset;\n"
"border: 1px solid  #4F4F4F;\n"
"color: #4F4F4F;\n"
"background: #FFFFFF;\n"
"border-radius:10px;\n"
"}\n"
"\n"
":pressed {\n"
"border-style: inset;\n"
"color: white;\n"
"background: #4F4F4F;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"")
        self.sign_in_button.setObjectName("sign_in_button")
        self.class_view_frame = QtWidgets.QFrame(mainwindow)
        self.class_view_frame.setGeometry(QtCore.QRect(449, 630, 500, 140))
        self.class_view_frame.setMinimumSize(QtCore.QSize(250, 100))
        self.class_view_frame.setMaximumSize(QtCore.QSize(500, 140))
        self.class_view_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.class_view_frame.setStyleSheet("*{\n"
"position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.class_view_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.class_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.class_view_frame.setObjectName("class_view_frame")
        self.class_view_cass_name_label = QtWidgets.QLabel(self.class_view_frame)
        self.class_view_cass_name_label.setGeometry(QtCore.QRect(10, 0, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.class_view_cass_name_label.setFont(font)
        self.class_view_cass_name_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.class_view_cass_name_label.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 18px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px")
        self.class_view_cass_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.class_view_cass_name_label.setWordWrap(True)
        self.class_view_cass_name_label.setObjectName("class_view_cass_name_label")
        self.class_view_class_des_label = QtWidgets.QLabel(self.class_view_frame)
        self.class_view_class_des_label.setGeometry(QtCore.QRect(10, 50, 481, 81))
        self.class_view_class_des_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.class_view_class_des_label.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.class_view_class_des_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.class_view_class_des_label.setWordWrap(True)
        self.class_view_class_des_label.setObjectName("class_view_class_des_label")
        self.post_single_button = QtWidgets.QFrame(mainwindow)
        self.post_single_button.setGeometry(QtCore.QRect(280, 550, 461, 70))
        self.post_single_button.setMinimumSize(QtCore.QSize(0, 70))
        self.post_single_button.setMaximumSize(QtCore.QSize(461, 70))
        self.post_single_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.post_single_button.setStyleSheet("*{position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.post_single_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post_single_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post_single_button.setObjectName("post_single_button")
        self.post_single_heading = QtWidgets.QLabel(self.post_single_button)
        self.post_single_heading.setGeometry(QtCore.QRect(10, 0, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.post_single_heading.setFont(font)
        self.post_single_heading.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.post_single_heading.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15\n"
"px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.post_single_heading.setObjectName("post_single_heading")
        self.post_single_timings = QtWidgets.QLabel(self.post_single_button)
        self.post_single_timings.setGeometry(QtCore.QRect(10, 40, 441, 21))
        self.post_single_timings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.post_single_timings.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.post_single_timings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.post_single_timings.setObjectName("post_single_timings")
        self.as_frame = QtWidgets.QFrame(mainwindow)
        self.as_frame.setGeometry(QtCore.QRect(730, 40, 248, 120))
        self.as_frame.setMinimumSize(QtCore.QSize(0, 120))
        self.as_frame.setMaximumSize(QtCore.QSize(99999, 120))
        self.as_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.as_frame.setStyleSheet("*{\n"
"position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.as_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.as_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.as_frame.setObjectName("as_frame")
        self.dynamic_name_label = QtWidgets.QLabel(self.as_frame)
        self.dynamic_name_label.setGeometry(QtCore.QRect(10, 0, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dynamic_name_label.setFont(font)
        self.dynamic_name_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_name_label.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 20px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;\n"
"")
        self.dynamic_name_label.setWordWrap(True)
        self.dynamic_name_label.setObjectName("dynamic_name_label")
        self.dynamic_in_label = QtWidgets.QLabel(self.as_frame)
        self.dynamic_in_label.setGeometry(QtCore.QRect(10, 60, 231, 21))
        self.dynamic_in_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_in_label.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.dynamic_in_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dynamic_in_label.setObjectName("dynamic_in_label")
        self.dynamic_sub_label = QtWidgets.QLabel(self.as_frame)
        self.dynamic_sub_label.setGeometry(QtCore.QRect(10, 90, 231, 21))
        self.dynamic_sub_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_sub_label.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.dynamic_sub_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dynamic_sub_label.setObjectName("dynamic_sub_label")
        self.as_frame_2 = QtWidgets.QFrame(mainwindow)
        self.as_frame_2.setGeometry(QtCore.QRect(110, 670, 241, 120))
        self.as_frame_2.setMinimumSize(QtCore.QSize(0, 120))
        self.as_frame_2.setMaximumSize(QtCore.QSize(99999, 120))
        self.as_frame_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.as_frame_2.setStyleSheet("*{\n"
"position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.as_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.as_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.as_frame_2.setObjectName("as_frame_2")
        self.dynamic_name_label_2 = QtWidgets.QLabel(self.as_frame_2)
        self.dynamic_name_label_2.setGeometry(QtCore.QRect(10, 0, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dynamic_name_label_2.setFont(font)
        self.dynamic_name_label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_name_label_2.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 20px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;\n"
"")
        self.dynamic_name_label_2.setWordWrap(True)
        self.dynamic_name_label_2.setObjectName("dynamic_name_label_2")
        self.dynamic_in_label_2 = QtWidgets.QLabel(self.as_frame_2)
        self.dynamic_in_label_2.setGeometry(QtCore.QRect(10, 60, 231, 21))
        self.dynamic_in_label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_in_label_2.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.dynamic_in_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dynamic_in_label_2.setObjectName("dynamic_in_label_2")
        self.dynamic_sub_label_2 = QtWidgets.QLabel(self.as_frame_2)
        self.dynamic_sub_label_2.setGeometry(QtCore.QRect(10, 90, 231, 21))
        self.dynamic_sub_label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_sub_label_2.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.dynamic_sub_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dynamic_sub_label_2.setObjectName("dynamic_sub_label_2")
        self.as_frame_3 = QtWidgets.QFrame(mainwindow)
        self.as_frame_3.setGeometry(QtCore.QRect(20, 230, 351, 120))
        self.as_frame_3.setMinimumSize(QtCore.QSize(0, 120))
        self.as_frame_3.setMaximumSize(QtCore.QSize(99999, 120))
        self.as_frame_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.as_frame_3.setStyleSheet("*{\n"
"position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.as_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.as_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.as_frame_3.setObjectName("as_frame_3")
        self.dynamic_name_label_3 = QtWidgets.QLabel(self.as_frame_3)
        self.dynamic_name_label_3.setGeometry(QtCore.QRect(10, 0, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dynamic_name_label_3.setFont(font)
        self.dynamic_name_label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_name_label_3.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 20px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;\n"
"")
        self.dynamic_name_label_3.setWordWrap(True)
        self.dynamic_name_label_3.setObjectName("dynamic_name_label_3")
        self.dynamic_in_label_3 = QtWidgets.QLabel(self.as_frame_3)
        self.dynamic_in_label_3.setGeometry(QtCore.QRect(10, 60, 231, 21))
        self.dynamic_in_label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_in_label_3.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.dynamic_in_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dynamic_in_label_3.setObjectName("dynamic_in_label_3")
        self.dynamic_sub_label_3 = QtWidgets.QLabel(self.as_frame_3)
        self.dynamic_sub_label_3.setGeometry(QtCore.QRect(10, 90, 341, 21))
        self.dynamic_sub_label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_sub_label_3.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.dynamic_sub_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dynamic_sub_label_3.setObjectName("dynamic_sub_label_3")
        self.username_label = QtWidgets.QFrame(mainwindow)
        self.username_label.setGeometry(QtCore.QRect(20, 390, 451, 150))
        self.username_label.setMinimumSize(QtCore.QSize(0, 120))
        self.username_label.setMaximumSize(QtCore.QSize(99999, 150))
        self.username_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.username_label.setStyleSheet("*{\n"
"position: absolute;\n"
"width: 370px;\n"
"height: 110px;\n"
"left: 7px;\n"
"top: 28px;\n"
"\n"
"background: rgba(0, 0, 0, 0.05);\n"
"border: 1px solid rgba(0, 0, 0, 0.3);\n"
"box-sizing: border-box;\n"
"border-radius: 10px}")
        self.username_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_label.setObjectName("username_label")
        self.dynamic_name_label_6 = QtWidgets.QLabel(self.username_label)
        self.dynamic_name_label_6.setGeometry(QtCore.QRect(10, 0, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dynamic_name_label_6.setFont(font)
        self.dynamic_name_label_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_name_label_6.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 20px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;\n"
"")
        self.dynamic_name_label_6.setWordWrap(True)
        self.dynamic_name_label_6.setObjectName("dynamic_name_label_6")
        self.sub_date = QtWidgets.QLabel(self.username_label)
        self.sub_date.setGeometry(QtCore.QRect(10, 60, 181, 21))
        self.sub_date.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sub_date.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.sub_date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sub_date.setObjectName("sub_date")
        self.pushButton_3 = QtWidgets.QPushButton(self.username_label)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 110, 121, 28))
        self.pushButton_3.setStyleSheet("*{\n"
"font-family: Inter;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"align-items: center;\n"
"border-style: inset;\n"
"border: 1px solid  #4F4F4F;\n"
"color: #4F4F4F;\n"
"background: #FFFFFF;\n"
"border-radius:10px;\n"
"}\n"
"\n"
":pressed {\n"
"border-style: inset;\n"
"color: white;\n"
"background: #4F4F4F;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.username_label)
        self.label.setGeometry(QtCore.QRect(10, 110, 71, 30))
        self.label.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 20px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.username_label)
        self.lineEdit.setGeometry(QtCore.QRect(90, 110, 113, 30))
        self.lineEdit.setStyleSheet("position: static;\n"
"width: 535px;\n"
"height: 53px;\n"
"left: 0px;\n"
"top: 0px;\n"
"\n"
"/* White */\n"
"\n"
"background: #FFFFFF;\n"
"/* Dark / Medium */\n"
"\n"
"border: 2px solid #4F4F4F;\n"
"box-sizing: border-box;\n"
"border-radius: 7px;\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.username_label)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 110, 93, 30))
        self.pushButton_4.setStyleSheet("*{\n"
"font-family: Inter;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"/* identical to box height */\n"
"\n"
"align-items: center;\n"
"\n"
"/* Grey / Light */\n"
"\n"
"color: white;\n"
"background: #4F4F4F;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
":pressed {\n"
"    border-style: inset;\n"
"    border: 1px solid  #4F4F4F;\n"
"color: #4F4F4F;\n"
"background: #FFFFFF;\n"
"}\n"
"/* Inside auto layout */\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.dynamic_file_name_label_6 = QtWidgets.QLabel(self.username_label)
        self.dynamic_file_name_label_6.setGeometry(QtCore.QRect(200, 60, 241, 21))
        self.dynamic_file_name_label_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dynamic_file_name_label_6.setStyleSheet("position: absolute;\n"
"left: 20px;\n"
"right: 30px;\n"
"top: 10px;\n"
"bottom: 10px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 37px;\n"
"letter-spacing: 0.05em;\n"
"background: rgba(0, 0, 0, 0.01);\n"
"color: #000000;\n"
"border:0px;")
        self.dynamic_file_name_label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dynamic_file_name_label_6.setObjectName("dynamic_file_name_label_6")

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Form"))
        self.post_button.setText(_translate("mainwindow", "Text Label"))
        self.label_6.setText(_translate("mainwindow", "Name"))
        self.label_7.setText(_translate("mainwindow", "Time"))
        self.comment.setText(_translate("mainwindow", "Comment"))
        self.user.setText(_translate("mainwindow", "User"))
        self.pushButton.setText(_translate("mainwindow", "Menu"))
        self.sign_up_button.setText(_translate("mainwindow", "Sign Up"))
        self.sign_in_button.setText(_translate("mainwindow", "Already a user? Sign In"))
        self.class_view_cass_name_label.setText(_translate("mainwindow", "Class Name"))
        self.class_view_class_des_label.setText(_translate("mainwindow", "Des"))
        self.post_single_heading.setText(_translate("mainwindow", "Heading"))
        self.post_single_timings.setText(_translate("mainwindow", "Timings"))
        self.dynamic_name_label.setText(_translate("mainwindow", "Name"))
        self.dynamic_in_label.setText(_translate("mainwindow", "In Date: 17-12-2001 12:12"))
        self.dynamic_sub_label.setText(_translate("mainwindow", "Las Date: 17-12-2001 12:12"))
        self.dynamic_name_label_2.setText(_translate("mainwindow", "Name"))
        self.dynamic_in_label_2.setText(_translate("mainwindow", "In Date: 17-12-2001 12:12"))
        self.dynamic_sub_label_2.setText(_translate("mainwindow", "Las Date: 17-12-2001 12:12"))
        self.dynamic_name_label_3.setText(_translate("mainwindow", "Name"))
        self.dynamic_in_label_3.setText(_translate("mainwindow", "In Date: 17-12-2001 12:12"))
        self.dynamic_sub_label_3.setText(_translate("mainwindow", "Las Date: 17-12-2001 12:12"))
        self.dynamic_name_label_6.setText(_translate("mainwindow", "Username"))
        self.sub_date.setText(_translate("mainwindow", "In Date: 17-12-2001 12:12"))
        self.pushButton_3.setText(_translate("mainwindow", "Download File"))
        self.label.setText(_translate("mainwindow", "Marks:"))
        self.pushButton_4.setText(_translate("mainwindow", "Submit"))
        self.dynamic_file_name_label_6.setText(_translate("mainwindow", "File Name:"))
import temp_rc
