# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\tejas\Desktop\22-01-22\create_posts.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(563, 631)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(541, 291))
        self.frame_2.setMaximumSize(QtCore.QSize(541, 291))
        self.frame_2.setStyleSheet("#frame_2{/* Auto layout */\n"
"\n"
"display: flex;\n"
"flex-direction: column;\n"
"align-items: flex-start;\n"
"padding: 40px 25px;\n"
"\n"
"position: absolute;\n"
"width: 593px;\n"
"height: 594px;\n"
"left: calc(50% - 593px/2 - 0.5px);\n"
"top: 243px;\n"
"\n"
"/* White */\n"
"\n"
"background: #FFFFFF;\n"
"/* Grey / Dark */\n"
"\n"
"border: 1px solid #D1D1D1;\n"
"box-sizing: border-box;\n"
"border-radius: 8px;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.post_heading_posts = QtWidgets.QLabel(self.frame_2)
        self.post_heading_posts.setGeometry(QtCore.QRect(20, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.post_heading_posts.setFont(font)
        self.post_heading_posts.setStyleSheet("position: absolute;\n"
"width: 233px;\n"
"height: 60px;\n"
"left: 92px;\n"
"top: 48px;\n"
"\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 30px;\n"
"line-height: 60px;\n"
"/* identical to box height */\n"
"\n"
"letter-spacing: 0.05em;\n"
"text-decoration-line: underline;\n"
"text-transform: capitalize;\n"
"\n"
"color: #000000;\n"
"")
        self.post_heading_posts.setObjectName("post_heading_posts")
        self.des = QtWidgets.QLabel(self.frame_2)
        self.des.setGeometry(QtCore.QRect(20, 60, 511, 131))
        self.des.setMaximumSize(QtCore.QSize(511, 16777215))
        self.des.setStyleSheet("background: rgba(196, 196, 196, 0.1);\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 30px;\n"
"/* identical to box height */\n"
"\n"
"letter-spacing: 0.05em;\n"
"text-transform: capitalize;\n"
"\n"
"color: #000000;")
        self.des.setScaledContents(False)
        self.des.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.des.setWordWrap(True)
        self.des.setObjectName("des")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 391, 41))
        self.label_2.setStyleSheet("font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 15px;\n"
"line-height: 30px;\n"
"/* identical to box height */\n"
"\n"
"letter-spacing: 0.05em;\n"
"text-transform: capitalize;\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 210, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 60, 511, 131))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.post_heading_posts.setText(_translate("Form", "Create Post"))
        self.des.setText(_translate("Form", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec."))
        self.label_2.setText(_translate("Form", "Files: "))
        self.pushButton_2.setText(_translate("Form", "Download"))
